"""Generate docs/DATA_MODEL.md from the SQLAlchemy metadata (spec §7, §17).

    python scripts/generate_erd.py            # write docs/DATA_MODEL.md
    python scripts/generate_erd.py --check    # fail if the committed copy is stale

The ERD is never hand-drawn: every table, column, key and foreign-key
relationship comes from the registered ORM models, so the diagram cannot
drift from the schema without CI noticing.
"""

from __future__ import annotations

import difflib
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

from sqlalchemy import UniqueConstraint

if TYPE_CHECKING:
    from sqlalchemy import Column, Table

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "DATA_MODEL.md"

PURPOSE = """\
The entity-relationship diagram (Mermaid), generated from the SQLAlchemy
metadata and never hand-drawn (spec §7, §17), plus the owning bounded
context of every table and the list of global (non-tenant) tables."""


def _load_metadata() -> tuple[object, object]:
    """Import every module's tables, then return (Base, registry)."""
    import creatoriqx_api.tables  # noqa: F401  # registers models on Base.metadata
    from creatoriqx_api.platform.db import Base

    return Base, Base.registry


def _owner(table_name: str, registry: object) -> str:
    """The module that owns ``table_name``, read from its mapped class's module path."""
    for mapper in registry.mappers:  # type: ignore[attr-defined]
        if mapper.local_table.name == table_name:
            parts: list[str] = mapper.class_.__module__.split(".")
            if "modules" in parts:
                return str(parts[parts.index("modules") + 1])
            return "?"
    return "?"


_TYPE_NAMES: dict[str, str] = {
    "Uuid": "uuid",
    "String": "string",
    "Integer": "int",
    "Boolean": "boolean",
    "DateTime": "timestamp",
    "JSONB": "jsonb",
    "Enum": "enum",
}


def _column_type(column: Column[Any]) -> str:
    name = type(column.type).__name__
    return _TYPE_NAMES.get(name, name.lower())


def _column_keys(column: Column[Any], table: Table) -> str:
    keys: list[str] = []
    if column.primary_key:
        keys.append("PK")
    if column.foreign_keys:
        keys.append("FK")
    for constraint in table.constraints:
        if (
            isinstance(constraint, UniqueConstraint)
            and column.name in constraint.columns
            and "UK" not in keys
        ):
            keys.append("UK")
    return ", ".join(keys)


def _entity_block(table: Table) -> list[str]:
    lines = [f"    {table.name} {{"]
    for column in table.columns:
        keys = _column_keys(column, table)
        suffix = f' "{keys}"' if keys else ""
        lines.append(f"        {_column_type(column)} {column.name}{suffix}")
    lines.append("    }")
    return lines


def _relationship_lines(tables: list[Table]) -> list[str]:
    lines: list[str] = []
    for table in tables:
        for fk in sorted(table.foreign_keys, key=lambda fk: fk.column.table.name):
            lines.append(f'    {fk.column.table.name} ||--o{{ {table.name} : "{fk.parent.name}"')
    return lines


def _mermaid(tables: list[Table]) -> str:
    lines = ["erDiagram"]
    for table in tables:
        lines.extend(_entity_block(table))
    lines.extend(_relationship_lines(tables))
    return "\n".join(lines)


def _is_tenant_scoped(table: Table) -> bool:
    return "workspace_id" in table.columns


def _render() -> str:
    base, registry = _load_metadata()
    tables = sorted(base.metadata.tables.values(), key=lambda t: t.name)  # type: ignore[attr-defined]

    ownership_rows = "\n".join(
        f"| `{t.name}` | {_owner(t.name, registry)} | {'yes' if _is_tenant_scoped(t) else 'no'} |"
        for t in tables
    )
    non_tenant = [t for t in tables if not _is_tenant_scoped(t)]
    global_tables = "\n".join(f"- `{t.name}`" for t in non_tenant) or "- none"

    return f"""# CreatorIQX Data Model

> **Generated by `scripts/generate_erd.py`** from the SQLAlchemy metadata (spec §7, §17).
> Do not hand-edit the diagram or the tables below; run the script again after
> adding or changing a table. CI fails if this file is stale.

## Purpose

{PURPOSE}

## Entity-relationship diagram

```mermaid
{_mermaid(tables)}
```

## Table ownership

Every table has exactly one owning bounded context (spec §3); other modules
read it only through that module's public interface or domain events.

| Table | Owning module | Tenant-scoped (`workspace_id`) |
|---|---|---|
{ownership_rows}

## Global (non-tenant) tables

Tables with no `workspace_id` column. These sit outside row-level security
by design (spec §6): either they are global identity (`users`) or a platform
table that must be read across every tenant (`outbox_events`, read by the
relay worker).

{global_tables}
"""


def write() -> None:
    # Bytes, not write_text: on Windows write_text emits CRLF, which the repo's
    # mixed-line-ending hook rejects. The committed document uses LF.
    OUTPUT.write_bytes(_render().encode("utf-8"))
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")


def check() -> bool:
    expected = _render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current == expected:
        print("Data model document is up to date.")
        return True
    diff = difflib.unified_diff(
        current.splitlines(), expected.splitlines(), "committed", "generated", lineterm=""
    )
    print("Data model document is STALE. Run: python scripts/generate_erd.py")
    print("\n".join(list(diff)[:60]))
    return False


def main(argv: list[str]) -> int:
    if argv == ["--check"]:
        return 0 if check() else 1
    if not argv:
        write()
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
