import createFetchClient, { type ClientOptions } from "openapi-fetch";
import type { paths } from "./schema.js";

/**
 * A fully-typed openapi-fetch client over the committed OpenAPI document
 * (openapi.json, generated by scripts/export_openapi.py in apps/api). The
 * `paths` type comes from schema.d.ts, generated by openapi-typescript -
 * changing a response or request type in the API changes `paths`, which
 * breaks any caller here that no longer matches (the acceptance test this
 * ticket is built around).
 */
export function createApiClient(options: ClientOptions) {
  return createFetchClient<paths>(options);
}

export type { paths } from "./schema.js";
