// PLACEHOLDER: generated by `pnpm --filter @creatoriqx/api-client run generate`
// from ../openapi.json. This sandbox cannot reach the npm registry to run
// openapi-typescript, so this file is a stand-in until CI resolves it
// (see docs/PROGRESS.md's "how to run the gates from a sandbox" note).
export type paths = Record<string, never>;
export type components = { schemas: Record<string, never> };
